### ISSUE TITLE
boringssl compatibility

### ISSUE THREAD

**Issue by janmojzis** [AGWA/titus#3]
Hello,
are You planing to make it compatible with boringssl?
Currently compilation fails:
c++ -Wall -Wextra -pedantic -O2 -std=c++11 -I../include   -c -o child.o child.cpp
c++ -Wall -Wextra -pedantic -O2 -std=c++11 -I../include   -c -o common.o common.cpp
c++ -Wall -Wextra -pedantic -O2 -std=c++11 -I../include   -c -o util.o util.cpp
c++ -Wall -Wextra -pedantic -O2 -std=c++11 -I../include   -c -o dh.o dh.cpp
c++ -Wall -Wextra -pedantic -O2 -std=c++11 -I../include   -c -o keyserver.o keyserver.cpp
c++ -Wall -Wextra -pedantic -O2 -std=c++11 -I../include   -c -o rsa_client.o rsa_client.cpp
rsa_client.cpp: In function ‘int {anonymous}::rsa_client_private_decrypt(int, const unsigned char_, unsigned char_, RSA_, int)’:
rsa_client.cpp:55:70: error: ‘RSA_get_app_data’ was not declared in this scope
   uintptr_t key_id = reinterpret_cast<uintptr_t>(RSA_get_app_data(rsa));
                                                                      ^
rsa_client.cpp: In function ‘int {anonymous}::rsa_client_private_encrypt(int, const unsigned char_, unsigned char_, RSA_, int)’:
rsa_client.cpp:75:70: error: ‘RSA_get_app_data’ was not declared in this scope
   uintptr_t key_id = reinterpret_cast<uintptr_t>(RSA_get_app_data(rsa));
                                                                      ^
rsa_client.cpp: In function ‘RSA_METHOD\* {anonymous}::get_rsa_client_method()’:
rsa_client.cpp:95:12: error: ‘RSA_METHOD’ has no member named ‘rsa_priv_enc’
   if (!ops.rsa_priv_enc) {
            ^
rsa_client.cpp:96:34: error: ‘RSA_get_default_method’ was not declared in this scope
    ops = _RSA_get_default_method();
                                  ^
rsa_client.cpp:97:8: error: ‘RSA_METHOD’ has no member named ‘rsa_priv_enc’
    ops.rsa_priv_enc = rsa_client_private_encrypt;
        ^
rsa_client.cpp:98:8: error: ‘RSA_METHOD’ has no member named ‘rsa_priv_dec’
    ops.rsa_priv_dec = rsa_client_private_decrypt;
        ^
rsa_client.cpp: In function ‘openssl_unique_ptr<evp_pkey_st> rsa_client_load_private_key(uintptr_t, RSA_)’:
rsa_client.cpp:125:51: error: ‘RSA_set_method’ was not declared in this scope
  RSA_set_method(rsa.get(), get_rsa_client_method());
                                                   ^
rsa_client.cpp:126:66: error: ‘RSA_set_app_data’ was not declared in this scope
  if (!RSA_set_app_data(rsa.get(), reinterpret_cast<void*>(key_id))) {
                                                                  ^
<builtin>: recipe for target 'rsa_client.o' failed
make: **\* [rsa_client.o] Error 1

Script used for compilation attached (titus.sh.txt)

[titus.sh.txt](https://github.com/AGWA/titus/files/40427/titus.sh.txt)

**Comment by AGWA** [comment]
I don't think BoringSSL compatibility makes sense for titus.  Google is developing BoringSSL explicitly for their own internal use, and makes no guarantees of API stability.  And titus is not a typical application since it uses several esoteric OpenSSL functions to make out-of-process RSA work.  These are exactly the types of functions that Google has removed from BoringSSL, as your build log indicates.

See https://www.imperialviolet.org/2015/10/17/boringssl.html and https://boringssl.googlesource.com/boringssl/ for more information about what BoringSSL is trying to accomplish.

On the plus side, titus protects you against OpenSSL vulnerabilities, so you needn't worry about flaws present in OpenSSL but not BoringSSL.
